services:
  app:
    build: .
    container_name: something-back
    ports:
      - '8000:8000'
    env_file:
      - .env
    # depends_on:
    #   - db
    restart: unless-stopped

#   db:
#     image: postgres:17
#     container_name: something-postgres
#     environment:
#       POSTGRES_DB: something_db
#       POSTGRES_USER: something_user
#       POSTGRES_PASSWORD: something_password
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     restart: unless-stopped

# volumes:
#   postgres_data:

